'use client';
import {useEffect,useState} from 'react';
import {BookOpen,ArrowUpRight,Download,Plus,Link2,FileText,ShieldCheck,Pencil,EyeOff,Eye} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {theme,type Project} from '@/lib/project-theme';
import ProjectIcon from './project-icon';
import type {Resource} from '@/lib/resources';
const blank=(projectId:string):Resource=>({id:crypto.randomUUID(),project_id:projectId,title:'',author:'',description:'',url:'',file_key:'',filename:'',size:0,hidden:0});
export default function Library({project,admin,canAdmin=false,viewer=null,signInUrl="/login"}:{project:Project;admin:boolean;canAdmin?:boolean;viewer?:string|null;signInUrl?:string}){
 const [rows,setRows]=useState<Resource[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Resource|null>(null),[file,setFile]=useState<File|null>(null);
 async function load(){setError('');try{const res=await fetch('/api/resources?project='+encodeURIComponent(project.id));const d=await res.json() as {error:string;resources:Resource[];key:string;size:number};if(!res.ok)throw Error(d.error);setRows(d.resources);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[project.id]);
 async function persist(r:Resource){const res=await fetch('/api/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});const d=await res.json() as {error:string;resources:Resource[];key:string;size:number};if(!res.ok)throw Error(d.error);}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setError('');setMessage('');try{const next={...draft};if(file){if(file.size>4*1024*1024||!file.size)throw Error('Selecciona un archivo de entre 1 byte y 4 MB.');const res=await fetch('/api/upload',{method:'POST',body:file});const d=await res.json() as {error:string;resources:Resource[];key:string;size:number};if(!res.ok)throw Error(d.error);Object.assign(next,{file_key:d.key,filename:file.name,size:d.size});setDraft(next);setFile(null);}await persist(next);setDraft(null);setFile(null);setMessage('Recurso guardado. Ya está disponible en la biblioteca.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function visibility(r:Resource){setBusy(true);setError('');try{await persist({...r,hidden:r.hidden?0:1});await load();setMessage(r.hidden?'Recurso publicado.':'Recurso oculto. Puedes volver a publicarlo.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=rows.filter(r=>admin||!r.hidden);
 return <div className={"project-surface layout-"+project.layout} style={theme(project)}><header><a className="brand" href="/"><span className="brand-icon"><ProjectIcon name={project.icon} size={23}/></span><span>Biblioteca<span className="brand-sub">ENMANUEL ROSA</span></span></a><nav>{viewer?<><span className="viewer-name">{viewer}</span>{admin?<><a href={"/p/"+project.code}>Ver proyecto</a><a href="/admin/activity">Historial de accesos</a></>:canAdmin&&<a href={"/admin/projects/"+project.id}><ShieldCheck size={16}/> Administración</a>}<a href="/logout" target="_top">Salir</a></>:<a href={signInUrl} target="_top">Iniciar sesión con Google</a>}</nav></header>
 <main><div className="intro"><div><p className="eyebrow">PROYECTO / {project.code}</p><h1>{project.name}</h1><p className="intro-copy">{project.description}</p></div><div className="topic"><ProjectIcon name={project.icon} size={40}/><strong>{project.code}</strong><a href="/">Ver todos los proyectos</a></div></div>
 <div className="workspace"><section className="collection"><div className="section-heading"><div><p className="eyebrow">{admin?'PANEL DE ADMINISTRACIÓN':'BIBLIOGRAFÍAS Y ARCHIVOS'}</p><h2>Recursos <span>{loading?'—':visible.length.toString().padStart(2,'0')}</span></h2></div>{admin&&<Button disabled={busy} onClick={()=>{setDraft(blank(project.id));setFile(null);setMessage('');setError('');}}><Plus size={17}/> Añadir recurso</Button>}</div>
 {error&&<div className="notice error" role="alert">{error} <button onClick={load}>Reintentar carga</button></div>}{message&&<div className="notice" role="status">{message}</div>}
 {draft&&<form className="editor" onSubmit={save}><h3>{rows.some(r=>r.id===draft.id)?'Editar recurso':'Nuevo recurso'}</h3><label>Título<Input required maxLength={250} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Autor, institución o año<Input maxLength={500} value={draft.author} onChange={e=>setDraft({...draft,author:e.target.value})}/></label><label>Enlace de la bibliografía<Input type="url" placeholder="https://" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Descripción (opcional)<Textarea maxLength={3000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Adjuntar archivo · máximo 4 MB<Input type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{draft.filename&&<p className="muted">Archivo guardado: {draft.filename}</p>}<p className="muted">Añade un enlace, un archivo o ambos. El contenido publicado será visible para quienes visiten la página.</p><div className="form-actions"><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar recurso'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>{setDraft(null);setFile(null);}}>Cancelar</Button></div></form>}
 {loading?<p className="loading" role="status">Cargando recursos…</p>:visible.length===0&&!error?<div className="loading">Todavía no hay recursos publicados.</div>:<div className="resources">{visible.map((r,i)=><article className={r.hidden?'resource hidden-resource':'resource'} key={r.id}><span className="number">{(i+1).toString().padStart(2,'0')}</span><div className="resource-content"><div className="resource-meta">{r.file_key?<><FileText size={14}/> ARCHIVO</>:<><Link2 size={14}/> REFERENCIA WEB</>}{!!r.hidden&&<span> · OCULTO</span>}</div><h3>{r.title}</h3><p className="author">{r.author}</p>{r.description&&<p className="description">{r.description}</p>}<div className="resource-actions">{r.url&&<a href={'/access/'+r.id+'?action=open_link'} target="_blank" rel="noopener noreferrer">Consultar fuente <ArrowUpRight size={16}/></a>}{r.file_key&&<a href={'/access/'+r.id+'?action=download'}>Descargar archivo <Download size={16}/></a>}</div>{r.filename&&<p className="file-meta">{r.filename} · {(r.size/1024/1024).toFixed(2)} MB</p>}{admin&&<div className="admin-actions"><button disabled={busy} onClick={()=>{setDraft({...r});setFile(null);window.scrollTo({top:210,behavior:'smooth'});}}><Pencil size={14}/> Editar</button><button disabled={busy} onClick={()=>visibility(r)}>{r.hidden?<Eye size={14}/>:<EyeOff size={14}/>} {r.hidden?'Publicar':'Ocultar'}</button></div>}</div></article>)}</div>}
 </section><aside><div className="qr-card"><span className="eyebrow">CONSULTA Y COMPARTE</span><h2>Comparte<br/>este proyecto.</h2><img src={"/api/projects/"+project.id+"/qr"} alt={"Código QR de "+project.name} width={216} height={216}/><p>Escanéalo para acceder a las bibliografías y los archivos actualizados.</p><a className="qr-download" href={"/api/projects/"+project.id+"/qr?download=1"} download><Download size={17}/> Descargar QR</a></div><div className="aside-note"><BookOpen size={20}/><p>Para abrir fuentes o descargar archivos debes iniciar sesión. Antes de continuar verás el aviso de registro de acceso.</p></div></aside></div></main><footer><span>Biblioteca de Enmanuel Rosa</span><span>{project.name}</span></footer></div>;
}
